apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-ner-uk
  labels:
    app.kubernetes.io/name: service-ner-uk
    app.kubernetes.io/component: web
  namespace: rabbits
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: service-ner-uk
      app.kubernetes.io/component: web
  template:
    metadata:
      labels:
        app.kubernetes.io/name: service-ner-uk
        app.kubernetes.io/component: web
    spec:
      containers:
        - name: service-ner-uk
          image: artem1sobolev/service-ner-uk:1.0.1
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: rabbitmq
            - secretRef:
                name: rabbitmq-creds

